# Generated by Django 2.2.16 on 2021-12-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0010_update_backend'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBlockHardwareChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('content_id', models.CharField(max_length=100)),
                ('is_checking_audio_enabled', models.BooleanField(default=False)),
                ('is_checking_microphone_enabled', models.BooleanField(default=False)),
                ('is_checking_camera_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
