# Generated by Django 2.2.16 on 2025-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0011_courseblockhardwarechecker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoredexamstudentattempthistory',
            name='completed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
