# Generated by Django 2.2.16 on 2025-07-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0012_add_index_to_proctoredexamstudentattempthistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseblockhardwarechecker',
            unique_together={('user_id', 'content_id')},
        ),
    ]
