# Generated by Django 2.2.12 on 2026-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0013_auto_20250701_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoredexamstudentattempt',
            name='removal_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
